table Dim_Product
	lineageTag: 7436fa74-9cac-4091-bba9-212b9adad770

	column category
		dataType: string
		lineageTag: e97cf077-0e38-4b8a-b1d1-57fba285779c
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column item
		dataType: string
		lineageTag: a9be1597-8f1e-49be-a365-fdb9819f87ab
		summarizeBy: none
		sourceColumn: item

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: int64
		formatString: 0
		lineageTag: 94e55885-23b0-4b2d-aa5f-4deae21fdf51
		summarizeBy: none
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

	column Product_ID
		dataType: int64
		formatString: 0
		lineageTag: 467dbe3c-afb7-4159-b9df-5c623b784262
		summarizeBy: none
		sourceColumn: Product_ID

		annotation SummarizationSetBy = Automatic

	partition Dim_Product = m
		mode: import
		source =
				let
				    Source = Fact_Sales,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"category", "item", "unit_price"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Index", "Product_ID"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

