table Fact_Sales
	lineageTag: f7d41980-2e37-4ec4-a9d3-91e1976282e7

	column sale_id
		dataType: int64
		formatString: 0
		lineageTag: f810b879-d00c-4c20-9c17-a571adf72b00
		summarizeBy: sum
		sourceColumn: sale_id

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 90e0256d-603c-43dd-96cf-2f56e2544c8e
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: b14ac7d3-3be7-4fb0-84d1-c9d7ba7ede5a
			defaultHierarchy: LocalDateTable_e155e855-279f-4e58-893b-fc82657ab0ec.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column city
		dataType: string
		lineageTag: 26e7cbf5-9bcb-4f8e-aed1-75b88d3ce3cc
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column store_format
		dataType: string
		lineageTag: 6de243bb-f244-4439-938f-e3d3e630b542
		summarizeBy: none
		sourceColumn: store_format

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 580a4399-ad3c-4050-84ab-a512cb2adf67
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column item
		dataType: string
		lineageTag: 30c1364b-24a2-4402-a986-1165bd983bf5
		summarizeBy: none
		sourceColumn: item

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: int64
		formatString: 0
		lineageTag: 32be2f8c-0c85-4935-8c25-085d4bb1b2bc
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: int64
		formatString: 0
		lineageTag: 13d5544e-c2bc-489a-8208-6004a25408fa
		summarizeBy: sum
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

	column sales_amount
		dataType: double
		lineageTag: cf95fce9-89e5-45b9-aeb5-08c38ad3d405
		summarizeBy: sum
		sourceColumn: sales_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Fact_Sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\HP\Brewmetrics-bi\brewmetrics_sales.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"sale_id", Int64.Type}, {"date", type date}, {"city", type text}, {"store_format", type text}, {"category", type text}, {"item", type text}, {"quantity", Int64.Type}, {"unit_price", Int64.Type}, {"sales_amount", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

